version: "3"

services:
  steam:
    build: ./steam-service
    ports:
      - 5000:80
    deploy:
      restart_policy:
        condition: on-failure
  mining:
    build: ./mining-service
    ports:
      - 6000:80
    deploy:
      restart_policy:
        condition: on-failure
