version: "3"

services:
  steam:
    build: ./steam-service
    ports:
      - 5000:8080
    deploy:
      restart_policy:
        condition: on-failure

  mining:
    build: ./mining-service
    ports:
      - 5500:8080
    deploy:
      restart_policy:
        condition: on-failure

  main-server:
    build: ./backend
    ports:
      - 4000:8080
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - steam
